// Optional development check: install Playwright, or pass PLAYWRIGHT_MODULE.
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const modulePath=process.env.PLAYWRIGHT_MODULE;
const {chromium}=await import(modulePath?pathToFileURL(modulePath).href:'playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1600,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const output=fileURLToPath(new URL('../../../local/artifacts/browser/',import.meta.url));
await mkdir(output,{recursive:true});
try{
  await page.goto('http://127.0.0.1:8077');
  await page.waitForFunction(()=>window.workshop);
  await page.locator('#scale').selectOption('2400');
  await page.screenshot({path:output+'menu.png'});
  await page.locator('#start').click();
  await page.waitForFunction(()=>window.workshop.status.tick>20);
  await page.waitForFunction(()=>[...document.querySelectorAll('#roster img')].length===5&&[...document.querySelectorAll('#roster img')].every(img=>img.complete&&img.naturalWidth>0));
  let status=await page.evaluate(()=>window.workshop.status);
  assert.equal(status.started,true);assert.ok(status.units>=2400);assert.equal(status.imported,true);
  await page.mouse.move(495,165);await page.mouse.down();await page.mouse.move(635,450,{steps:6});await page.mouse.up();
  assert.ok((await page.evaluate(()=>window.workshop.status)).selected>0);
  await page.keyboard.press('F2');
  await page.waitForFunction(()=>window.workshop.status.selected>0);
  await page.keyboard.press('Control+1');
  await page.keyboard.press('Escape');
  assert.equal((await page.evaluate(()=>window.workshop.status)).selected,0);
  await page.keyboard.press('1');
  assert.ok((await page.evaluate(()=>window.workshop.status)).selected>0);
  await page.keyboard.press('a');
  await page.mouse.click(810,420);
  await page.keyboard.down('Shift');await page.mouse.click(880,490,{button:'right'});await page.keyboard.up('Shift');
  await page.locator('[data-formation="wedge"]').click();
  await page.locator('[data-type="soldier"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('#queue button').length>0);
  await page.locator('#pause').click();
  assert.equal((await page.evaluate(()=>window.workshop.status)).paused,true);
  await page.screenshot({path:output+'battle.png'});
  await page.locator('#menu').click();await page.locator('#save').click();
  await page.locator('#load').click();
  assert.equal((await page.evaluate(()=>window.workshop.status)).paused,false);
  await page.locator('#help').click();await page.locator('#close-help').click();
  await page.mouse.move(740,410);await page.mouse.wheel(0,-700);
  await page.screenshot({path:output+'tactical.png'});
  await page.locator('#menu').click();await page.locator('#scale').selectOption('6000');await page.locator('#start').click();
  await page.waitForFunction(()=>window.workshop.status.tick>=80);
  status=await page.evaluate(()=>window.workshop.status);
  assert.ok(status.units>=5900);
  const performanceText=await page.locator('#perf').textContent();
  await page.screenshot({path:output+'stress.png'});
  await page.setViewportSize({width:1100,height:800});
  await page.screenshot({path:output+'compact.png'});
  assert.deepEqual(errors,[]);
  const fallback=await browser.newPage();
  await fallback.route('**/local-content/bfme-content.json',route=>route.fulfill({status:404,body:'Not imported'}));
  await fallback.goto('http://127.0.0.1:8077');await fallback.waitForFunction(()=>window.workshop);
  assert.equal((await fallback.evaluate(()=>window.workshop.status)).imported,false);
  await fallback.locator('#start').click();await fallback.waitForFunction(()=>window.workshop.status.tick>2);
  await fallback.close();
  const report={passed:true,status,performanceText,pageErrors:errors};
  await writeFile(output+'browser-smoke.json',JSON.stringify(report,null,2));console.log(report);
}catch(error){console.error('Browser state:',await page.evaluate(()=>({status:window.workshop?.status,scale:document.querySelector('#scale')?.value,dialogs:[...document.querySelectorAll('dialog')].map(d=>({id:d.id,open:d.open}))})));await page.screenshot({path:output+'failure.png'});throw error;}finally{await browser.close();}
